# Generated by Django 5.0.6 on 2024-08-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_payment_payment_link_payment_payment_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='статус платежа'),
        ),
    ]
