# Generated by Django 5.0.6 on 2024-08-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_subscribed',
            field=models.BooleanField(default=False, verbose_name='подписка'),
        ),
    ]
